apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: student-management-ingress
  namespace: student-management
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: student.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: student-management-service
                port:
                  number: 80
